### ISSUE TITLE
Combined Service Discovery

### ISSUE THREAD

**Issue by michalszynkiewicz** [smallrye/smallrye-stork#111]
add an option to use service discovery information from multiple providers (e.g. Consul and Eureka) for a single service

**Comment by benDeMtp** [comment]
To follow up on quarkus insight # 70
Why can I need multiple providers ?
1) On a hybrid infrastructure with VMs on one side and kubernetes and pods on the other side.
Pods discover other pods using internal discovery service, but need consul to discover VM.

![Diagramme vierge-2](https://user-images.githubusercontent.com/22216215/141814718-e2d7fed9-0682-403a-ad47-670a651ba56e.png)

2) Dedicated discovery service. On consul used for infrastructure services ( logging, mail, etc.) and another consul dedicated to project-level services

**Comment by michalszynkiewicz** [comment]
@benDeMtp right now it is possible to use different service discovery providers for different services (so, IIUC, your second scenario should work okay).
This task is about enabling usage of multiple providers for a single service.
