### ISSUE TITLE
About the integration of Eurake with Stork

### ISSUE THREAD

**Issue by janyyy** [smallrye/smallrye-stork#216]
Can you provide a demo of stork integrating Eurake? Including Eurake Server and Client, thank you very much.

**Comment by janyyy** [comment]
Based on Qurakus framework

**Comment by michalszynkiewicz** [comment]
Which part specifically is troublesome for you? [This integration test](https://github.com/quarkusio/quarkus/tree/main/integration-tests/rest-client-reactive-stork) is a simple example of how to use Stork with Quarkus, for Eureka you simply change the type of the service discovery and and the [documentation for Eureka](http://smallrye.io/smallrye-stork/1.0.0/eureka/) shows the options for configuring Eurerka with Stork.

**Comment by michalszynkiewicz** [comment]
over time we will add more and more documentation and examples but I don't think this specific one is of a high need at the moment.
Of course, feel free to add an

**Comment by michalszynkiewicz** [comment]
I will close this issue, please let us know if you have any specific problems integrationg Stork with Eureka
