### ISSUE TITLE
Loadbalacing using the request scoped information

### ISSUE THREAD

**Issue by ivansenic** [smallrye/smallrye-stork#286]
I am trying to understand if there is any option to implement the custom load balancing that would depend on the request scoped bean when Stork is integrated into Quarkus.

For example, there is a nice explanation in the documentation about service labels and how can you decide to send some portion of traffic to V1 and some to V2. However, let's imaging that I have a header value with my incoming request with the value of the depending service to use. Is there any way to access the request scoped information when I decide what service to load balance to?

Is there any way I can configure Stork with Quarkus using the CDI and inject arbitrary beans? If this would be possible, then I guess this would work. Or for example, can I access the ArC beans in some kind of a static way from that custom load balancing config?

**Comment by rsvoboda** [comment]
This is an interesting question, @aureamunoz can you provide some insight?

**Comment by aureamunoz** [comment]
Hi, yes! This [PR](https://github.com/quarkusio/quarkus/pull/28296) introduced a Stork Filter for URIs starting with `stork://`or `storks://`so with the methods mentioned by @Ladicek you should be able to access the request

**Comment by cescoffier** [comment]
Completed in https://github.com/quarkusio/quarkus/pull/28296
