### ISSUE TITLE
Kubernetes ServiceDiscovery

### ISSUE THREAD

**Issue by michalszynkiewicz** [smallrye/smallrye-stork#33]
Implementing DNS for Kubernetes seems like a good start but can we go further?

This issue is to figure out what are the most common patterns for service discovery and client side load balancing on Kubernetes that Stork can help with. 

- add a key-value pairs as kuberneters strategy selectors (label=value)

**Comment by aureamunoz** [comment]
I think this can be closed. 
cc @michalszynkiewicz
