### ISSUE TITLE
Cannot resolve configuration item 'service-registar.type'

### ISSUE THREAD

**Issue by ensctom** [smallrye/smallrye-stork#591]
I am using the quarkus with the following depednecies

```
 <!-- https://mvnrepository.com/artifact/io.quarkus/quarkus-smallrye-stork-deployment -->
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-stork-deployment</artifactId>
    <version>3.1.0.Final</version>
</dependency>
<!-- https://mvnrepository.com/artifact/io.smallrye.stork/stork-service-discovery-eureka -->
<dependency>
    <groupId>io.smallrye.stork</groupId>
    <artifactId>stork-service-discovery-eureka</artifactId>
    <version>2.2.0</version>
</dependency>
```

According to the docs http://smallrye.io/smallrye-stork/2.2.0/service-discovery/eureka/#service-registration-configuration
registry is added like so

>quarkus.stork.my-service.service-registrar.type=eureka
quarkus.stork.my-service.service-registrar.eureka-host=localhost
quarkus.stork.my-service.service-registrar.eureka-port=8761

However, this is not the behavior I am seeing with

```
quarkus.stork.myservice.service-registrar.type=eureka

```
Intellj complains that `service-registrar.type` cannot be resolved. 

I assume the reason is because none of the service registry code has been added to quarkus 
https://github.com/quarkusio/quarkus/tree/main/extensions/smallrye-stork/runtime/src/main/java/io/quarkus/stork . I can only see classes related to service discovery only

Not sure if this is the root cause, maybe I am missing a dependency?

Any help would be appreciated.

**Comment by aureamunoz** [comment]
This issue has been addressed in Stork 2.3.0 and [this PR](https://github.com/quarkusio/quarkus/pull/34372/files) takes it into account in Quarkus.
