### ISSUE TITLE
Is there any way to get the host of the response?

### ISSUE THREAD

**Issue by cdmikechen** [smallrye/smallrye-stork#623]
We currently use a combination of stork and rest-client with quarkus 2.16.6, and we use consul for service discovery.
Now we want to get the downstream host based on stork request, is there currently a way to get it via stork?
We tried to get the response and found that the only response we get via rest-client is the `context-length` and `context-type`.

Thanks

**Comment by cescoffier** [comment]
no feedback from reporter.
