### ISSUE TITLE
Code listings blank when viewing web docs

### ISSUE THREAD

**Issue by kdubb** [smallrye/smallrye-stork#626]
All of the, what appear to be code listings, are blank when viewing the documentation website.

This is from the `Concepts` page:
<img width="803" alt="Screenshot 2023-07-24 at 6 00 54 PM" src="https://github.com/smallrye/smallrye-stork/assets/787655/b758e5a5-0761-4578-a412-a44f44199a72">

This is from the `Programmatic API` page:
<img width="820" alt="Screenshot 2023-07-24 at 6 01 01 PM" src="https://github.com/smallrye/smallrye-stork/assets/787655/ba69b6dc-3916-4e0c-b987-881986af90ea">

Screenshots are from Safari `16.5.2` but the issue is also visible using Crome `114.0.5735.198`. 

The OS is `macOS 13.4.1`.

**Comment by kdubb** [comment]
Note that some other literal blocks seems fine.

XML works:
<img width="775" alt="Screenshot 2023-07-24 at 6 07 21 PM" src="https://github.com/smallrye/smallrye-stork/assets/787655/884043ef-984d-43d5-b80e-3b425781ff18">

YAML works:
<img width="789" alt="Screenshot 2023-07-24 at 6 08 00 PM" src="https://github.com/smallrye/smallrye-stork/assets/787655/cfac3640-fc39-4130-a27e-86f642699b67">

Appears to just be code listings.

**Comment by cescoffier** [comment]
Thanks for reporting! 

I don't really know the reason, but the source code inclusion is not working anymore. Fortunately, we have a macro we can use. See #629

**Comment by cescoffier** [comment]
Ok, it's fixed! Sorry about that.... still don't totally understand what happened.
