### ISSUE TITLE
Eureka Service Discovery Documentation mentions Consul

### ISSUE THREAD

**Issue by crossbone-magister** [smallrye/smallrye-stork#638]
Hi,

while reading the documentation I've noticed that the [Service Registration](https://smallrye.io/smallrye-stork/2.3.2/service-discovery/eureka/#service-registration-configuration) for the Eureka Service Discovery page mentions Consul:
"Consul service registrar is configured with the following parameters:".

I thought about directly opening a pull request with the change. The missing parameters list left me wondering if maybe a more complex change is required.
If that's not the case I can gladly contribute myself.

**Comment by aureamunoz** [comment]
Hi!
Good catch! Go ahead with the PR if you want.
The list of parameters should be displayed, there is nothing to do, I will take a look at that.

:-)

**Comment by cescoffier** [comment]
Closed by #639
