### ISSUE TITLE
Outdated Addresses in Consul

### ISSUE THREAD

**Issue by MehmetNuri** [smallrye/smallrye-stork#738]
I have multiple Consul services with the same address but different ports. I register multiple instances with Consul in Quarkus, but when one or more of the instances are closed, it still keeps the old address in memory.  Even if I use refresh-period in the settings, the addresses remain old. Instances need to be updated periodically.

**Note:** Even if I write a special Load Balancer, it does not make sense because the examples from Consul are the same. 

```properties
quarkus.stork.red-service.service-discovery=consul
quarkus.stork.red-service.service-discovery.consul-host=localhost
quarkus.stork.red-service.service-discovery.consul-port=8500
quarkus.stork.red-service.service-discovery.type=consul
quarkus.stork.red-service.load-balancer.type=round-robin
quarkus.stork.red-service.refresh-period=2s

```

![image](https://github.com/smallrye/smallrye-stork/assets/9196888/41143152-83b3-4e99-8a9d-eafb48ec4679)

**Quarkus Version:**  3.6.3
**Java Version:** 21

**Comment by MehmetNuri** [comment]
The bug was fixed when I made the following setting
quarkus.stork.red-service.service-discovery.refresh-period=10s

**Comment by aureamunoz** [comment]
Hi, thank you!
