### ISSUE TITLE
Expand ServiceInstance definition

### ISSUE THREAD

**Issue by gytis** [smallrye/smallrye-stork#8]
The initial implementation of a `ServiceInstance` has a bare minimum of information. In the future it should have much more data such as host, port and schema. It should also have an option to include custom information such as credentials and labels.

**Comment by gytis** [comment]
cc @aureamunoz

**Comment by michalszynkiewicz** [comment]
we have a place for labels, etc now.
We may revisit credentials in the future but I will close this issue now
